export const SITE_URL = "https://www.contabilidadeportocon.com.br" as const;

export const PERSON = {
  name: "Portocon Contabilidade e Assessoria LTDA",
  nameShort: "Portocon",
  nickname: "portocon",
  jobTitle: "Contabilidade",
  jobTitleEn: "Accounting",
  description:
    "Portocon Contabilidade e Assessoria LTDA - Escritório de contabilidade em Brusque, SC, fundado por uma dupla de sócios com experiência de anos no mercado. Atendimento dedicado ao pequeno empresário. Contabilidade prática e moderna. Atendemos MEI, Simples Nacional e Lucro Presumido.",
  descriptionLong:
    "Portocon Contabilidade e Assessoria LTDA - Escritório de contabilidade em Brusque, SC, fundado por uma dupla de sócios com experiência de anos no mercado. Atendimento dedicado ao pequeno empresário. Contabilidade prática e moderna, com soluções digitais fáceis de usar e compromisso em encantar a cada atendimento.",
} as const;

export const SEO_KEYWORDS = [
  "Portocon",
  "Portocon Contabilidade e Assessoria LTDA",
  "contabilidade Portocon",
  "escritório Portocon",

  "contabilidade",
  "contador",
  "escritório de contabilidade",
  "contabilidade empresarial",
  "contabilidade para empresas",
  "contabilidade online",
  "contabilidade digital",
  "serviços contábeis",
  "abrir empresa",
  "abertura de empresa",
  "mudar de contador",
  "trocar contador",
  "mudança de contador",

  "contabilidade MEI",
  "contabilidade Simples Nacional",
  "contabilidade Lucro Presumido",
  "contabilidade para pequenas empresas",
  "contabilidade para micro empresas",
  "contabilidade para prestadores de serviço",
  "contabilidade para comércio",
  "contabilidade para indústria",

  "departamento fiscal",
  "departamento pessoal",
  "departamento contábil",
  "gestão fiscal",
  "gestão de impostos",
  "folha de pagamento",
  "obrigações acessórias",
  "declaração de imposto de renda",
  "DAS",
  "eSocial",
  "SPED",

  "contabilidade Brasil",
  "contabilidade SC",
  "contabilidade Santa Catarina",
  "contador brusque",
  "contador em Brusque",
  "contabilidade Brusque",
  "contabilidade em Brusque",
  "contador Brusque SC",
  "escritório de contabilidade Brusque",
  "contabilidade Santa Catarina Brusque",
  "contador região de Brusque",
  "contador Águas Claras Brusque",
  "abrir empresa Brusque",
  "contador para MEI Brusque",
  "mudar de contador Brusque",
  "melhor contador Brusque",
  "contador próximo Brusque",

  "contador online",
  "contador digital",
  "contabilidade simplificada",
  "contabilidade descomplicada",
  "contabilidade prática",
  "contabilidade moderna",
  "atendimento contábil",
  "suporte contábil",
  "consultoria contábil",
] as const;

export const DEFAULT_OG_IMAGE = {
  url: "/images/og-image.png",
  width: 1120,
  height: 630,
  alt: "Portocon Contabilidade e Assessoria LTDA | Escritório de Contabilidade",
} as const;
